### PR TITLE
Version attribute for RSS element added

### PR DESCRIPTION
**Pull request by ololower**
Based on google's XML specification 
https://support.google.com/merchants/answer/160589?hl=ru&ref_topic=2473799

### CODE REVIEW

**Comment by lizhi-0901** [comment]
hello, i'am using this bundle for a project, i noticed in your lastest commit for the rss version, you changed "1.0" to "2", is this a small bug?  thank you

**Comment by vitalybaev** [comment]
@ololower thanks for this pull request. However, I ask you for the following changes:

1. Class properties and vars should be `camelCased` (it's about `$rss_version`)
2. I agree with @lizhi-0901 - although I don't know about breaking changes from switching from RSS 1.0 to 2.0, it shouldn't be default without new major version. As for me - I prefer to add property (+ getter/setter) to Feed class, with default version of RSS - 1.0 with ability to change it

Could you change this?

**Comment by ololower** [comment]
Now the version is not specified explicitly at all. Perhaps you should keep this behavior and add the ability to set the version via the setter of the Feed class?

**Comment by vitalybaev** [comment]
Exactly, you are completely right. I'd like to save current behaviour - don't add version attribute at all by default. My point is to prevent any unexpected situations for package consumers. And in future, I'll ship new major version with version 2 by default

**Pull request merged**
